SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE users_roles;
SET FOREIGN_KEY_CHECKS = 1;


SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE roles;
SET FOREIGN_KEY_CHECKS = 1;


SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE database gogodb;
use gogodb;
